[env]
platform = espressif8266
board = esp12e
framework = arduino

monitor_speed = 115200

board_build.f_cpu = 80000000L ; 80MHz - minimal battery
board_build.flash_mode = dio  ; Dual I/O flash access

; HydroSensor (Regular)
[env:hydrosensor]
build_flags = 
    -std=c++17
    -Wall
    -Wextra
lib_deps =
    https://github.com/tzapu/WiFiManager.git # WifiManager
    bblanchon/ArduinoJson @ ^7.2.2 # JSON
    adafruit/Adafruit ADS1X15 @ ^2.4.0  # ADS1115 ADC Bus
    adafruit/Adafruit BusIO @ ^1.11.6 # BusIO

; HydroSensor Pro
[env:hydrosensor_pro]
build_flags = 
    -std=c++17
    -Wall
    -Wextra
    -D HARDWARE_PRO
lib_deps =
    https://github.com/tzapu/WiFiManager.git # WifiManager
    bblanchon/ArduinoJson @ ^7.2.2 # JSON
    adafruit/Adafruit ADS1X15 @ ^2.4.0  # ADS1115 ADC Bus
    adafruit/Adafruit SHT31 Library @ ^2.2.0  # SHT31-D Temp/Humidity
    adafruit/Adafruit TSL2591 Library @ ^1.4.3 # TSL2591 Light Sensor
    adafruit/Adafruit BusIO @ ^1.11.6 # BusIO
